/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseEChart: typeof import('./src/components/charts/BaseEChart.vue')['default']
    ChargeTableEdit: typeof import('./src/components/chargeTable/chargeTableEdit.vue')['default']
    ChargeTableRenderer: typeof import('./src/components/chargeTable/chargeTableRenderer.vue')['default']
    DoubleLineChartEdit: typeof import('./src/components/doubleLineChart/doubleLineChartEdit.vue')['default']
    DoubleLineChartRenderer: typeof import('./src/components/doubleLineChart/doubleLineChartRenderer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImageBlockEdit: typeof import('./src/components/imageBlock/imageBlockEdit.vue')['default']
    ImageBlockRenderer: typeof import('./src/components/imageBlock/imageBlockRenderer.vue')['default']
    MixedChartEdit: typeof import('./src/components/mixedChart/mixedChartEdit.vue')['default']
    MixedChartRenderer: typeof import('./src/components/mixedChart/mixedChartRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
